name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.92.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --workspace --release
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: target/release/discovery target/release/relay-node target/release/tor-client
          retention-days: 7
