name: Check

on:
  push:
  pull_request:

jobs:
  check:
    name: Compilation Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.92.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --workspace --all-targets --all-features
